resilience4j.circuitbreaker:
    instances:
        backendB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 60s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
